version: "2.3"
services:
  express:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8000
    restart: always
    environment:
      PORT: 8000
      MYSQL_USER: root
      MYSQL_DATABASE: docker-build
      MYSQL_PASSWORD: "1234"
      MYSQL_HOST: docker.for.mac.localhost
      MYSQL_PORT: 3308
    # depends_on:
    #   - exmysql
    # networks:
    #   - default
    #   - corn_net
# networks:
#   corn_net:
#     driver: bridge
