version: "2.3"
services:
  exmysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: always
    ports:
      - "3308:3308"
    expose:
      - 3308
    environment:
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=docker_build
      - MYSQL_USER=jeonghyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3308
  express:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:8000
    restart: always
    environment:
      PORT: 8000
      MYSQL_USER: root
      MYSQL_DATABASE: docker_build
      MYSQL_PASSWORD: 1234
      MYSQL_HOST: exmysql
    depends_on:
      - exmysql
