version: "2.3"
services:
  exmysql:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./docker/mysql:/var/lib/mysql
    # restart: always
    ports:
      - "3308:3308"
    expose:
      - 3308
    environment:
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=docker-build
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=1234
      - MYSQL_TCP_PORT=3308
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
